#!/bin/sh

[ "$(uci -q get network.zju.proto)" = "l2tp" ] && exit 0

sed -i '1i #30 23 * * * poweroff' /etc/crontabs/root
/etc/init.d/cron restart

uci	-q batch << EOF
	set dhcp.@dnsmasq[0].rebind_protection='0'
	commit dhcp

	set network.zju=interface
	set network.zju.proto='l2tp'
	set network.zju.server='lns.zju.edu.cn'
	set network.zju.mtu='1460'
	commit network

	delete firewall.@zone[1].network
	add_list firewall.@zone[1].network='wan'
	add_list firewall.@zone[1].network='wan6'
	add_list firewall.@zone[1].network='zju'
	commit firewall
EOF

/etc/init.d/dnsmasq restart
/etc/init.d/network restart
/etc/init.d/firewall restart

exit 0

