#!/bin/sh
# Auto reconnect ZJU L2TP. Put it in /etc/hotplug.d/iface/
([ ${INTERFACE} = 'zju' ] && [ ${ACTION} = 'ifdown' ]) || exit 0
# Don't disturb if there's no configured password
[ -n "$(uci -q get network.zju.password)" ] || exit 0

logger -p daemon.warn -t zjudown "ZJU L2TP seems down, wait for 20 seconds..."
# Wait enough time in case of the chaos at boot
sleep 20

CheckZJU() {
    ZJU_DOWN='0'
    if (ifstatus wan | grep -q '"up": true') && (ifstatus zju | grep -q '"up": false'); then
    # Only works when WAN DHCP is fine
        ZJU_DOWN='1'
    fi
    return ${ZJU_DOWN}
}

CheckZJU; ZJU_DOWN=$?
TrialCount=0
MAXTRIALNUM=2

# Tries at most ${MAXTRIALNUM} times
while [ ${ZJU_DOWN} = '1' ] && [ ${TrialCount} -lt ${MAXTRIALNUM} ]; do
    TrialCount=$(expr ${TrialCount} + 1)
    logger -p daemon.info -t zjudown "Start No.${TrialCount} trial..."
    ifup zju
    logger -p daemon.info -t zjudown "Wait for 15 seconds..."
    sleep 15
    CheckZJU; ZJU_DOWN=$?
done

if [ ${TrialCount} -ge ${MAXTRIALNUM} ]; then
    logger -p daemon.warn -t zjudown "All ${TrialCount} trials failed. Stop working."
fi

if [ ${ZJU_DOWN} = "0" ]; then
    logger -p daemon.warn -t zjudown "ZJU L2TP is working now."
fi

exit 0
