#!/bin/sh
# Auto reconnect ZJU L2TP. Put it in /etc/hotplug.d/iface/
([ ${INTERFACE} = 'zju' ] && [ ${ACTION} = 'ifdown' ]) || exit 0
# Don't disturb if there's no configured password
[ -n "$(uci -q get network.zju.password)" ] || exit 0

CheckZJU() {
	WHETHER2_RESTART_L2TP='norestart'
	if (ifstatus wan | grep -q '"up": true') && (ifstatus zju | grep -q '"up": false'); then
	# When WAN DHCP is fine and ZJU L2TP is down
		WHETHER2_RESTART_L2TP='restart'
	fi
	echo "${WHETHER2_RESTART_L2TP}"
}

# Wait enough time in case of the chaos at boot
logger -p daemon.warn -t zjudown 'ZJU L2TP seems down, wait for 20 seconds...'
sleep 20
L2TP_STATUS=$(CheckZJU)
# Tries ${MAXTRIALNUM} times at most
MAXTRIALNUM=2
TrialCount=0

while [ ${L2TP_STATUS} = 'restart' ] && [ ${TrialCount} -lt ${MAXTRIALNUM} ]; do
	TrialCount=$(expr ${TrialCount} + 1)
	logger -p daemon.info -t zjudown "Start No.${TrialCount} trial..."
	ifup zju
	logger -p daemon.info -t zjudown 'Wait for 15 seconds...'
	sleep 15
	L2TP_STATUS=$(CheckZJU)
done

if [ ${TrialCount} -ge ${MAXTRIALNUM} ]; then
	logger -p daemon.warn -t zjudown "All ${TrialCount} trials failed. Exit."
fi
if [ ${L2TP_STATUS} = 'norestart' ]; then
	logger -p daemon.warn -t zjudown 'ZJU L2TP is working now. Exit.'
fi

exit 0
