#!/bin/sh
# If ZJU L2TP lost while WAN DHCP works, the script would reconnect ZJU L2TP.
( [ ${INTERFACE} = zju ] && [ ${ACTION} =ifdown ] ) || exit 0
( ifstatus wan | grep -q '"up": true' ) || exit 0
logger -t zjudown "ZJU L2TP is down, wait for 5 seconds..."
sleep 5
( ifstatus wan | grep -q '"up": true' ) || exit 0
( ifstatus zju | grep -q '"up": true' ) && exit 0
logger -t zjudown "Reconnect ZJU L2TP..."
ifup zju
