name: Build RM-AC2100

on:
  schedule:
    - cron: 0 20 * * 4
  workflow_dispatch:

env:
  SOURCE_PROJECT: openwrt/openwrt
  SOURCE_BRANCH: openwrt-22.03
  VERSION_TAG: OpenWrt 22.03

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E swapoff -a
        sudo -E rm -f /swapfile
        sudo -E apt -qy autoremove --purge
        sudo -E apt -qy clean
        sudo -E rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt -qy update
        sudo -E apt -qy install asciidoc autoconf automake autopoint binutils build-essential bzip2 ccache curl device-tree-compiler ecj fastjar file flex g++ g++-multilib gawk gcc gcc-multilib gettext git gperf java-propose-classpath lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool p7zip-full patch pkgconf python3 python3-pip python3-ply qemu-utils rsync scons squashfs-tools subversion swig time uglifyjs unzip wget xsltproc zlib1g-dev
        sudo -E apt -qy clean

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Get source code
      uses: actions/checkout@v3
      with:
        repository: ${{ env.SOURCE_PROJECT }}
        ref: ${{ env.SOURCE_BRANCH }}
        path: 'openwrt'

    - name: Get last action cache
      id: load_chche
      uses: actions/cache@v3
      with:
        path: ./openwrt/action_cache_${{ hashFiles('./.github/RM2100_build_mark') }}.tar
        key: openwrt-rm2100-${{ hashFiles('./.github/RM2100_build_mark') }}

    - name: Restore cache files
      if: steps.load_chche.outputs.cache-hit == 'true'
      working-directory: ./openwrt
      run: |
        tar -xzf action_cache_*.tar
        mv ./action_cache/build_dir/ ./action_cache/dl/ ./action_cache/staging_dir/ -t ./
        rm -f ./action_cache_*.tar && rm -rf ./action_cache/
        echo "Files under openwrt directory: $(ls -lha)"

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Customize
      working-directory: ./openwrt
      run: |
        BUILD_DATE=$(date -d "8 hour" -u +%Y-%m-%d)
        sed -i "s/%D %V %C/$VERSION_TAG @$BUILD_DATE/g" package/base-files/files/etc/openwrt_release
        cp ../configs/RM2100_config ./.config
        make defconfig
        cat ./.config > ../configs/all_RM2100_config
        sh ./scripts/diffconfig.sh > ../configs/diff_RM2100_config

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "Using $(($(nproc)+1)) threads to compile."
        make -j $(($(nproc)+1)) download world

    - name: Prepare for release
      run: |
        echo "Last build mark: $(date -d "8 hour" -u +"%Y-%m-%d %H:%M")" > ./.github/RM2100_build_mark
        mkdir -p release_firmwares
        mv ./openwrt/bin/targets/ramips/mt7621/*-initramfs-kernel.bin ./release_firmwares/RM2100-initramfs-kernel.bin
        mv ./openwrt/bin/targets/ramips/mt7621/*-squashfs-sysupgrade.bin ./release_firmwares/RM2100-squashfs-sysupgrade.bin

    - name: Commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./.github/RM2100_build_mark ./configs/all_RM2100_config ./configs/diff_RM2100_config
        git commit -m "Auto update"
        git push origin main

    - name: Upload firmware to releases
      uses: ncipollo/release-action@v1.10.0
      with:
        name: latest rm2100 firmware
        tag: latest-rm2100
        artifacts: "release_firmwares/RM2100-initramfs-kernel.bin,release_firmwares/RM2100-squashfs-sysupgrade.bin"
        bodyFile: ".github/RM2100_build_mark"
        allowUpdates: true
        replacesArtifacts: true

    # It seems that GitHub's ${{ hashFiles }} execute before commands in the same step execute.
    # So make sure hashed File changed before the step.
    - name: Create cache file
      working-directory: ./openwrt
      run: |
        rm -rf ../release_firmwares
        make clean
        mkdir ./action_cache
        mv ./build_dir/ ./dl/ ./staging_dir/ -t ./action_cache
        tar -czf ./action_cache.tar ./action_cache
        mv action_cache.tar action_cache_${{ hashFiles('./.github/RM2100_build_mark') }}.tar
        rm -rf ./action_cache

    - name: Upload new action cache
      uses: actions/cache@v3
      with:
        path: ./openwrt/action_cache_${{ hashFiles('./.github/RM2100_build_mark') }}.tar
        key: openwrt-rm2100-${{ hashFiles('./.github/RM2100_build_mark') }}

