name: Build X86-64

on:
  schedule:
    - cron: 0 0 * * 5
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt -yq update
        sudo apt -yq install asciidoc autoconf automake autopoint binutils build-essential bzip2 ccache curl device-tree-compiler ecj fastjar file flex g++ g++-multilib gawk gcc gcc-multilib gettext git gperf java-propose-classpath lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool p7zip-full patch pkgconf python3 python3-pip python3-ply qemu-utils rsync scons squashfs-tools subversion swig tar time uglifyjs unzip wget xsltproc zlib1g-dev
        sudo apt -yq clean

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Get source code
      uses: actions/checkout@v3
      with:
        repository: immortalwrt/immortalwrt
        ref: openwrt-21.02
        path: 'openwrt'

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Customize
      working-directory: ./openwrt
      run: |
        sed -i 's/192\.168\.1\.1/192\.168\.6\.1/g' ./package/base-files/files/bin/config_generate
        BUILD_DATE=$(date -d "8 hour" -u +%Y-%m-%d)
        sed -i "s/%D %V %C/ImmortalWrt 21.02 @$BUILD_DATE/g" package/base-files/files/etc/openwrt_release
        mkdir -p ./files/etc/uci-defaults/
        cp ../custom/zju_localize ./files/etc/uci-defaults/
        rm ./feeds/luci/themes/luci-theme-argon/htdocs/luci-static/argon/img/bg1.jpg
        cp ../custom/wallhaven-dpepjo.jpg ./feeds/luci/themes/luci-theme-argon/htdocs/luci-static/argon/img/bg1.jpg
        cp ../configs/X64_config ./.config
        make defconfig
        cp ./.config ../configs/new_all_X64_config
        sh ./scripts/diffconfig.sh > ../configs/new_diff_X64_config

    - name: Diff config
      id: diff_config
      working-directory: ./configs
      run: |
        if [ "$(diff -q new_all_X64_config all_X64_config)" != "" ]
        then
          echo "::set-output name=state::changed"
          rm -f all_X64_config diff_X64_config
          mv new_all_X64_config all_X64_config
          mv new_diff_X64_config diff_X64_config
        else
          echo "Configs have not changed."
        fi

    - name: Commit config files
      if: steps.diff_config.outputs.state == 'changed'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./configs/all_X64_config ./configs/diff_X64_config
        git commit -m "Update config files"
        git push origin main

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "Using $(($(nproc)+1)) threads to compile..."
        make -j $(($(nproc)+1)) download world

    - name: Prepare for release
      run: |
        echo "RELEASE_BODY=Firmware built at: $(date -d "8 hour" -u +"%Y-%m-%d %H:%M")" >> $GITHUB_ENV
        mkdir release_path
        mv ./openwrt/bin/targets/x86/64/* ./release_path
        cd ./release_path
        tar -czf packages.tgz ./packages
        rm -rf ../openwrt ./packages

    - name: Delete old release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: latest-x64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to releases
      uses: ncipollo/release-action@v1.10.0
      with:
        name: latest x64 firmware
        tag: latest-x64
        artifacts: release_path/*
        body: ${{ env.RELEASE_BODY }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 15
        keep_minimum_runs: 1

