name: Build OpenWrt

on:
  workflow_dispatch:

env:
  SOURCE_BRANCH: openwrt-22.03

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E swapoff -a
        sudo -E rm -f /swapfile
        sudo -E docker image prune -a -f
        sudo -E apt -y autoremove --purge
        sudo -E apt -y clean
        sudo -E rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt -y update
        sudo -E apt -y install asciidoc autoconf automake autopoint binutils build-essential bzip2 ccache curl device-tree-compiler ecj fastjar file flex g++ g++-multilib gawk gcc gcc-multilib gettext git gperf java-propose-classpath lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool p7zip-full patch pkgconf python3 python3-pip python3-ply qemu-utils rsync scons squashfs-tools subversion swig time uglifyjs unzip wget xsltproc zlib1g-dev
        sudo -E apt -y clean

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get source code
      uses: actions/checkout@v3
      with:
        repository: openwrt/openwrt
        ref: ${{ env.SOURCE_BRANCH }}
        path: 'openwrt'

    - name: Install & Update feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Customize
      working-directory: ./openwrt
      run: |
        BUILD_DATE=$(date -d "8 hour" -u +%Y-%m-%d)
        sed -i "s/%D %V %C/OpenWrt 22.03 @$BUILD_DATE/g" package/base-files/files/etc/openwrt_release
        cp ../configs/openwrt_config.txt ./.config
        make defconfig
        cat ./.config > ../configs/all_openwrt_config.txt
        sh ./scripts/diffconfig.sh > ../configs/diff_openwrt_config.txt

    - name: Commit config files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./configs/all_openwrt_config.txt ./configs/diff_openwrt_config.txt
        git commit --allow-empty -m "Upload config files"
        git push origin main

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(($(nproc)+1)) thread compile"
        make -j $(($(nproc)+1)) download world

    - name : Upload firmware to artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: |
          openwrt/bin/targets/ramips/mt7621/*-initramfs-kernel.bin
          openwrt/bin/targets/ramips/mt7621/*-squashfs-sysupgrade.bin
        retention-days: 3

    #- name : Upload all to artifact
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: openwrt
    #    path: openwrt/bin/targets/ramips/mt7621
    #    retention-days: 3

