name: Build X86-64

on:
  schedule:
    - cron: 0 2 * * 3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize environment
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt -yq update
        sudo apt -yq install asciidoc autoconf automake autopoint binutils build-essential bzip2 ccache curl device-tree-compiler ecj fastjar file flex g++ g++-multilib gawk gcc gcc-multilib gettext git gperf java-propose-classpath lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool p7zip-full patch pkgconf python3 python3-pip python3-ply qemu-utils rsync scons squashfs-tools subversion swig tar time uglifyjs unzip wget xsltproc zlib1g-dev zstd
        sudo apt -yq clean

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Get source code
      uses: actions/checkout@v3
      with:
        repository: immortalwrt/immortalwrt
        ref: openwrt-21.02
        path: 'openwrt'

    - name: Set path
      run: |
        mkdir -p releases artifacts
        echo "MAIN_PATH=$PWD" >> $GITHUB_ENV
        echo "OPENWRT_PATH=$PWD/openwrt" >> $GITHUB_ENV
        echo "RELEASES_PATH=$PWD/releases" >> $GITHUB_ENV
        echo "ARTIFACTS_PATH=$PWD/artifacts" >> $GITHUB_ENV

    - name: Restore build cache-1
      continue-on-error: true
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: Build-X64.yml
        workflow_conclusion: success
        name: last_build_cache

    - name: Restore build cache-2
      run: |
        if [ -e last_build_cache.zip ]; then
          unzip -o last_build_cache.zip
          tar --zstd -xf Build_cache.tar.zst
          mv dl build_dir staging_dir -t $OPENWRT_PATH
          rm -f Build_cache.tar.zst
          echo "Last build cache restored."
        else
          echo "Cache file not found."
        fi

    - name: Update & Install feeds
      run: |
        cd $OPENWRT_PATH
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Customize
      run: |
        cd $OPENWRT_PATH
        sed -i 's/192\.168\.1\.1/192\.168\.6\.1/g' ./package/base-files/files/bin/config_generate
        wget -q https://downloads.immortalwrt.org/releases/21.02-SNAPSHOT/targets/x86/64/packages/Packages.gz
        zgrep -m 1 "Depends: kernel (=.*)$" Packages.gz | sed 's/.*-\(.*\))/\1/' > .vermagic
        rm -f Packages.gz
        sed -i 's/^\(.\).*vermagic$/\1cp $(TOPDIR)\/.vermagic $(LINUX_DIR)\/.vermagic/' ./include/kernel-defaults.mk
        BUILD_DATE=$(date -d "8 hour" -u +%Y-%m-%d)
        sed -i "s/%D %V %C/ImmortalWrt 21.02 @$BUILD_DATE/g" ./package/base-files/files/etc/openwrt_release
        mkdir -p ./files/etc/uci-defaults/
        cp $MAIN_PATH/custom/zju_localize ./files/etc/uci-defaults/
        rm ./feeds/luci/themes/luci-theme-argon/htdocs/luci-static/argon/img/bg1.jpg
        cp $MAIN_PATH/custom/*.jpg ./feeds/luci/themes/luci-theme-argon/htdocs/luci-static/argon/img/bg1.jpg
        cp $MAIN_PATH/configs/X64_config ./.config
        make defconfig
        cp ./.config $MAIN_PATH/configs/new_all_X64_config
        sh ./scripts/diffconfig.sh > $MAIN_PATH/configs/new_diff_X64_config

    - name: Diff config
      id: diff_config
      run: |
        cd $MAIN_PATH/configs
        if [ "$(diff -q new_all_X64_config all_X64_config)" != "" ]; then
          echo "::set-output name=state::changed"
          rm -f all_X64_config diff_X64_config
          mv new_all_X64_config all_X64_config
          mv new_diff_X64_config diff_X64_config
        else
          echo "Configs have not changed."
        fi

    - name: Commit config files
      if: steps.diff_config.outputs.state == 'changed'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add $MAIN_PATH/configs/all_X64_config $MAIN_PATH/configs/diff_X64_config
        git commit -m "Update config files"
        git push origin main

    - name: Build firmware
      run: |
        cd $OPENWRT_PATH
        du -h --max-depth=1
        echo "--------------------"
        echo "Using $(($(nproc)+1)) threads to compile..."
        make -j $(($(nproc)+1)) download world
        echo "RELEASE_BODY=Firmware built at: $(date -d "8 hour" -u +"%Y-%m-%d %H:%M")" >> $GITHUB_ENV
        echo "--------------------"
        du -h --max-depth=1

    - name: Delete old release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: latest-x64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Manage releases and artifacts
      run: |
        mv $OPENWRT_PATH/bin/targets/x86/64/* $RELEASES_PATH
        cd $RELEASES_PATH
        tar -czf packages.tgz ./packages --remove-files
        cd $OPENWRT_PATH
        make clean
        du -h --max-depth=1
        echo "--------------------"
        mv $OPENWRT_PATH/dl $OPENWRT_PATH/build_dir $OPENWRT_PATH/staging_dir -t $ARTIFACTS_PATH
        cd $ARTIFACTS_PATH
        tar --zstd -cf Build_cache.tar.zst * --remove-files
        rm -rf $OPENWRT_PATH

    - name: Upload to Releases
      uses: ncipollo/release-action@v1.10.0
      with:
        name: latest x64 firmware
        tag: latest-x64
        artifacts: ${{ env.RELEASES_PATH }}/*
        body: ${{ env.RELEASE_BODY }}

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: last_build_cache
        path: ${{ env.ARTIFACTS_PATH }}/Build_cache.tar.zst
        retention-days: 14

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 8
        keep_minimum_runs: 1

