name: Build ImmortalWrt

on:
  workflow_dispatch:

env:
  SOURCE_BRANCH: openwrt-21.02

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E swapoff -a
        sudo -E rm -f /swapfile
        sudo -E docker image prune -a -f
        sudo -E apt -y autoremove --purge
        sudo -E apt -y clean
        sudo -E rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt -y update
        sudo -E apt -y install asciidoc autoconf automake autopoint binutils build-essential bzip2 ccache curl device-tree-compiler ecj fastjar file flex g++ g++-multilib gawk gcc gcc-multilib gettext git gperf java-propose-classpath lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool p7zip-full patch pkgconf python3 python3-pip python3-ply qemu-utils rsync scons squashfs-tools subversion swig time uglifyjs unzip wget xsltproc zlib1g-dev 
        sudo -E apt -y clean

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get source code
      uses: actions/checkout@v3
      with:
        repository: immortalwrt/immortalwrt
        ref: ${{ env.SOURCE_BRANCH }}
        path: 'openwrt'

    - name: Install & Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Customize
      run: |
        cd openwrt
        BUILD_DATE=$(date -d "8 hour" -u +%Y-%m-%d)
        sed -i "s/%D %V %C/ImmortalWrt 21.02 @$BUILD_DATE/g" package/base-files/files/etc/openwrt_release
        sed -i 's/luci\.main\.lang=auto/luci\.main\.lang=zh_cn/g' package/emortal/default-settings/files/99-default-settings
        cp ../configs/immortalwrt_config.txt ./.config
        make defconfig
        rm ./feeds/luci/themes/luci-theme-argon/htdocs/luci-static/argon/img/bg1.jpg
        wget -q -O ./feeds/luci/themes/luci-theme-argon/htdocs/luci-static/argon/img/bg1.jpg https://w.wallhaven.cc/full/dp/wallhaven-dpepjo.jpg

    - name: Commit config files
      run: |
        cd openwrt
        cat ./.config > ../configs/all_immortalwrt_config.txt
        sh ./scripts/diffconfig.sh > ../configs/diff_immortalwrt_config.txt
        cd ..
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./configs/all_immortalwrt_config.txt ./configs/diff_immortalwrt_config.txt
        git commit --allow-empty -m "Upload config files"
        git push origin main

    - name: Build firmware
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j $(nproc) download world

    - name : Upload ext4-efi.img to artifact
      uses: actions/upload-artifact@v3
      with:
        name: ext4-combined
        path: openwrt/bin/targets/x86/64/*-ext4-combined-efi.img.gz
        retention-days: 3

    - name : Upload squashfs-efi.img to artifact
      uses: actions/upload-artifact@v3
      with:
        name: squashfs-combined
        path: openwrt/bin/targets/x86/64/*-squashfs-combined-efi.img.gz
        retention-days: 3

    #- name : Upload all to artifact
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: openwrt
    #    path: openwrt/bin/targets/x86/64
    #    retention-days: 3

