name: new

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Restore build cache-1
      continue-on-error: true
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: Build-RM2100.yml
        workflow_conclusion: success
        name: last_build_cache
        skip_unpack: true

    - name: Restore build cache-2
      run: |
        tree -a -s -L 3 | tee filelist

